package ant.com.spring.entities;
// Generated Aug 9, 2019 10:48:01 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "shop")
public class Product implements java.io.Serializable {

	private int id;
	private String name;
	private Integer price;
	private Integer typeId;
	private Integer quantity;
	private Integer sale;
	private String imgMain;
	private String img;
	private Date createdDate;

	public Product() {
	}

	public Product(int id) {
		this.id = id;
	}

	public Product(int id, String name, Integer price, Integer typeId, Integer quantity, Integer sale, String imgMain,
			String img, Date createdDate) {
		this.id = id;
		this.name = name;
		this.price = price;
		this.typeId = typeId;
		this.quantity = quantity;
		this.sale = sale;
		this.imgMain = imgMain;
		this.img = img;
		this.createdDate = createdDate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Column(name = "type_id")
	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "sale")
	public Integer getSale() {
		return this.sale;
	}

	public void setSale(Integer sale) {
		this.sale = sale;
	}

	@Column(name = "img_main")
	public String getImgMain() {
		return this.imgMain;
	}

	public void setImgMain(String imgMain) {
		this.imgMain = imgMain;
	}

	@Column(name = "img")
	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
